version: "3"

services:
  filetracker:
    image: jet-filetracker:latest
    container_name: filetracker
    command: "broker"
    ports: 
      - "12610:12610"
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    env_file: conf/redis-secret.env
    ports:
      - "6379:6379"
    networks:
      - back-tier

  worker:
    image: jet-filetracker:latest
    container_name: filetracker-worker
    command: "pool"
    depends_on:
      - filetracker
      - redis
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
